# Generated by Django 3.2.5 on 2022-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSPWebApp', '0002_remove_scoredatapuzzleone_dateadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreData2048',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
            ],
        ),
    ]
