# Generated by Django 3.2.5 on 2022-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSPWebApp', '0003_scoredata2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredata2048',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoredatapuzzleone',
            name='score',
            field=models.IntegerField(),
        ),
    ]
